FRC2240/RapidReact2022

src/main/cpp/Robot.cpp, src/main/include/Robot.h, vendordeps/Phoenix.json, vendordeps/REVLib.json
Added:
includes for Robot.h
Talon Motors (drivebase)
Differntial drive
Added motor groups
Fly safe
On branch speedy-boi
new file:   vendordeps/Phoenix.json
new file:   vendordeps/REVLib.json
=> Declared Drivebase

src/main/include/Robot.h
I added a few CANSparkMaxes in the header file
It's quick, really just a scramble to save future work
Fly safe
On branch speedy-boi
Your branch is up to date with 'origin/speedy-boi'.
=> Basic Motor IDs

src/main/cpp/Robot.cpp, src/main/include/Robot.h
Added the 13 motors, added the drive exponent and some other things
I don't know what else to say
Fly safe
On branch Messi
=> Added header files

src/main/cpp/Robot.cpp
Just name changing
Fly safe
On branch theTestsNeverBroke
=> Fixing code to fix the tests

src/main/cpp/Robot.cpp, src/main/include/Robot.h
Intake: Y
Uptake: A
Shooter Retract: RB
Shooter Fire: LB
Also I did some functions
Fly safe
On branch basic-control
=> Added a some controls

src/main/cpp/Robot.cpp, src/main/include/Robot.h
=> IneedtoPushitNow

src/main/cpp/Robot.cpp, src/main/include/Robot.h
Alpha Shooter and Beta Shooter PIDs
Fly safe
=> Added Shooter PIDs

src/main/cpp/Robot.cpp, src/main/include/Robot.h
=> cleaned up limelight code

src/main/cpp/Robot.cpp, src/main/include/Robot.h
Or fixed the git
+ Reverted to Crozby's commit that built
+ Fixed the current issues by commenting out old code
- REVIEW IS RECOMMENDED
Fly safe
On branch darnGit
=> I gixted the fix

.gitignore, src/main/cpp/Climber.cpp, src/main/cpp/Robot.cpp, src/main/cpp/Shooter.cpp, src/main/cpp/Take.cpp, src/main/include/Robot.h, src/main/include/Shooter.h, src/main/include/Take.h
=> Unfinished mess

src/main/cpp/Robot.cpp, src/main/cpp/Shooter.cpp
Changed some comments
Make a better teleop soon
Fly safe
On branch teleop-additions
modified:   src/main/cpp/Shooter.cpp
=> Code cleanup

src/main/cpp/Shooter.cpp, src/main/cpp/Take.cpp, src/main/include/Shooter.h
=> Merge this one

src/main/cpp/Shooter.cpp, src/main/cpp/Take.cpp, src/main/include/Shooter.h
Mostly dash changes, nothing very important 
##Basic info:
##Fixed Issue #{number}: {description}
##The following files were changed
##{changed files}
##Detailed info
##Talk about what exactly you did
##72 chars max
#What problem did you solve
#You can ramble
#Resolves: #{Issue number}
#See also: #{related issue}, #{another related issue}
-- Commit made by Jeff Bezos Stonerbot 
Fly safe
=> Added Limelight testing framework

src/main/cpp/Take.cpp, src/main/include/Take.h
Remove Color Sensors until we have the right cables.
=> Exceptions from unconnected Color Sensors

src/main/cpp/Take.cpp, src/main/include/Take.h
Have a terrible version tree for Valentines
=> Enums for real this time

src/main/cpp/Robot.cpp, src/main/cpp/Take.cpp, src/main/include/Take.h
I changed things to enums because:
- Erik wanted me to
- Reduces runtime error
- chars are kinda cringe
Notes:
+ Added enums
- Everything is public
- Might need review
Fly safe
On branch enums
modified:   src/main/cpp/Take.cpp
modified:   src/main/include/Take.h
=> Added Enums

src/main/cpp/Robot.cpp, src/main/cpp/Shooter.cpp, src/main/cpp/Take.cpp, src/main/include/Take.h
I changed it because it would fail during runtime if it remained in it's current state
Fly safe
On branch enum-revised
modified:   src/main/cpp/Shooter.cpp
modified:   src/main/cpp/Take.cpp
modified:   src/main/include/Take.h
=> Fixed issues relating to enums

src/main/cpp/Robot.cpp, src/main/cpp/Shooter.cpp, src/main/include/Shooter.h
Now it grabs data
Ask me for more info
Fly safe
On branch error-handling
Your branch is based on 'origin/error-handling', but the upstream is gone.
(use "git branch --unset-upstream" to fixup)
modified:   src/main/cpp/Shooter.cpp
modified:   src/main/include/Shooter.h
=> Better limelight code

src/main/cpp/Climber.cpp, src/main/cpp/Robot.cpp, src/main/cpp/Take.cpp, src/main/include/Climber.h, src/main/include/Take.h
Added a few constructors and updated take
constructors:
- changed due to simplicity
- Probably should be best practice in the future
Take update:
- Added options for when the wrong ball in in waiting room
Fly safe
On branch construction
modified:   src/main/cpp/Climber.cpp
modified:   src/main/cpp/Take.cpp
modified:   src/main/include/Climber.h
modified:   src/main/include/Take.h
=> Constructors and take updates

src/main/include/Climber.h
Just servo init, noting more
Fly safe
On branch servo
modified:   src/main/include/Climber.h
=> Added servos

src/main/cpp/Climber.cpp, src/main/cpp/Robot.cpp, src/main/cpp/Shooter.cpp, src/main/cpp/Take.cpp, src/main/include/Climber.h, src/main/include/Robot.h, src/main/include/Take.h
=> 2 24 climb testing

src/main/cpp/Climber.cpp, src/main/include/Climber.h
The code will now compile and not spam couts to the driver
Fly safe
On branch servo-cout-fix
modified:   src/main/cpp/Climber.cpp
modified:   src/main/include/Climber.h
=> Fixed bugs with couts

src/main/include/Climber.h
Fixed a shuffleboard issue with Matthew's help
Fly safe
On branch shuffleboard-light-patch
modified:   src/main/include/Climber.h
=> Matthew's fixes
